CLASS zcx_zone_iarc_mapping DEFINITION
  PUBLIC
  INHERITING FROM zcx_zone_iarc_root
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_zone_iarc_mapping IMPLEMENTATION.
ENDCLASS.
