PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONE_IARC_T003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONE_IARC_T003-PROVIDER_KEY .
    FIELD ZONE_IARC_T003-ENVIRONMENT .
    FIELD ZONE_IARC_T003-SERVICE_TYPE .
    FIELD ZONE_IARC_T003-ENDPOINT_URL .
    FIELD ZONE_IARC_T003-TIMEOUT_SEC .
    FIELD ZONE_IARC_T003-RETRY_COUNT .
    FIELD ZONE_IARC_T003-AUTH_TYPE .
    FIELD ZONE_IARC_T003-STRUST_PSE .
    FIELD ZONE_IARC_T003-SECSTORE_KEY .
    FIELD ZONE_IARC_T003-ACTIVE_FLG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONE_IARC_T003-PROVIDER_KEY .
    FIELD ZONE_IARC_T003-ENVIRONMENT .
    FIELD ZONE_IARC_T003-SERVICE_TYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
