PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONE_IARC_T001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONE_IARC_T001-BUKRS .
    FIELD ZONE_IARC_T001-ACTIVE_FLG .
    FIELD ZONE_IARC_T001-POLL_INTERVAL_MIN .
    FIELD ZONE_IARC_T001-ENVIRONMENT .
    FIELD ZONE_IARC_T001-COMP_TAX_NO .
    FIELD ZONE_IARC_T001-COMP_SERIAL_NO .
    FIELD ZONE_IARC_T001-ACC_USER_CODE .
    FIELD ZONE_IARC_T001-ACC_TAX_NO .
    FIELD ZONE_IARC_T001-ACC_PWD_KEY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONE_IARC_T001-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
