PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONE_IARC_T005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONE_IARC_T005-BUKRS .
    FIELD ZONE_IARC_T005-PO_MATCH .
    FIELD ZONE_IARC_T005-DEFAULT_HKONT .
    FIELD ZONE_IARC_T005-DEFAULT_MWSKZ .
    FIELD ZONE_IARC_T005-DEFAULT_KOSTL .
    FIELD ZONE_IARC_T005-DEFAULT_BLART .
    FIELD ZONE_IARC_T005-TOLERANCE_PCT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONE_IARC_T005-BUKRS .
    FIELD ZONE_IARC_T005-PO_MATCH .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
